### ISSUE TITLE
Linux installation

### ISSUE THREAD

**Issue by pasha9999** [viictorjs/Refrapy#9]
Ola, meu amigos! Como vai?

I've tried to install your code onte RedHat Linux 8. All installation steps (through Anaconda) run smooth, but when i tried to start - I got this error message

python Refrapick.py
Traceback (most recent call last):
  File "Refrapick.py", line 1851, in <module>
    app = Refrapick()
  File "Refrapick.py", line 35, in __init__
    self.iconbitmap("%s/images/ico_refrapy.ico"%getcwd())
  File "/apps/anaconda3/envs/refrapy/lib/python3.8/tkinter/__init__.py", line 2080, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "/home/_apps/Refrapy/Refrapy/images/ico_refrapy.ico" not defined

Do you have any idea how to resolve it?

Best regards,
Pavel

**Comment by pasha9999** [comment]
Short update.
I've converted icon to *.xbm file using ImageMagic ->

convert images/ico_refrapy.ico images/ico_refrapy.xbm

And change path to file to relative ->

self.iconbitmap("@images/ico_refrapy.xbm")

Now I can start the interface.
cheers,
Pavel

**Comment by akpopoola** [comment]
Hi,
This fix worked for me too on Ubuntu 20.04 by changing all the instances of .iconbitmap and using a .xbm file which I converted using ImageMagic. There was an error of "TclError: image "pyimage5" doesn't exist" when I run the code with Spyder. So avoid it if you are on Ubuntu.

**Comment by hyperNeo** [comment]
> Short update.
> I've converted icon to *.xbm file using ImageMagic ->
> 
> convert images/ico_refrapy.ico images/ico_refrapy.xbm
> 
> And change path to file to relative ->
> 
> self.iconbitmap("@images/ico_refrapy.xbm")
> 
> Now I can start the interface.
> cheers,
> Pavel

Omg, thank you so much !!!
This fix worked for me too on Parrot Linux
